"""Who's who, and which token belongs to them.

Secrets need identity: with one shared token the server cannot tell Wren from
Tobias Goreguts. `people.yaml` holds the identities (safe to commit, no secrets) and
`.people-tokens.json` maps each person's token to their key (never committed,
generated by tools/make_people_tokens.py).

A person's *identities* are their own key plus their role, so a secret
addressed to `dm` reaches whoever is currently the DM without naming them.
"""

from __future__ import annotations

import hmac
import json
from dataclasses import dataclass, field
from pathlib import Path

import yaml

TOKENS_FILE = ".people-tokens.json"


@dataclass
class Person:
    key: str
    name: str
    role: str = "player"
    character: str = ""

    @property
    def identities(self) -> frozenset[str]:
        return frozenset({self.key.lower(), self.role.lower()})

    @property
    def is_dm(self) -> bool:
        return self.role.lower() == "dm"


@dataclass
class People:
    members: dict[str, Person] = field(default_factory=dict)
    # token -> key. Kept separate from `members` so identities can be committed
    # and tokens cannot be.
    tokens: dict[str, str] = field(default_factory=dict)

    def resolve(self, token: str) -> Person | None:
        """Find the person holding this token, in constant time.

        Compares against every token rather than doing a dict lookup, so the
        time taken doesn't reveal how much of a guess was correct.
        """
        found: str | None = None
        for candidate, key in self.tokens.items():
            if hmac.compare_digest(token, candidate):
                found = key
        return self.members.get(found) if found else None

    @property
    def dms(self) -> list[Person]:
        return [p for p in self.members.values() if p.is_dm]

    def __bool__(self) -> bool:
        return bool(self.members)


def load(root: Path) -> People:
    """Load identities and tokens. Missing files mean the feature is off."""
    people = People()

    config = root / "people.yaml"
    if not config.exists():
        return people

    raw = yaml.safe_load(config.read_text(encoding="utf-8")) or {}
    for entry in raw.get("people") or []:
        key = str(entry.get("key", "")).strip().lower()
        if not key:
            continue
        people.members[key] = Person(
            key=key,
            name=entry.get("name", key),
            role=str(entry.get("role", "player")).strip().lower(),
            character=entry.get("character", ""),
        )

    tokens_path = root / TOKENS_FILE
    if tokens_path.exists():
        try:
            data = json.loads(tokens_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            data = {}
        for token, key in data.items():
            key = str(key).strip().lower()
            if key in people.members:
                people.tokens[str(token)] = key

    return people
