# Set up a named Cloudflare tunnel so the MCP server keeps a permanent URL.
#
# Quick tunnels (`cloudflared tunnel --url ...`) hand you a random
# trycloudflare.com address that dies when the process stops. A named tunnel is
# tied to your Cloudflare account and a hostname you own, so the address never
# changes and your players configure it once.
#
# Prerequisites, both of which are yours to do:
#   1. A Cloudflare account with a domain whose DNS Cloudflare manages.
#   2. `cloudflared tunnel login`, which opens a browser and asks you to pick
#      that domain. It writes ~/.cloudflared/cert.pem.
#
# Then:
#   .\tools\setup_named_tunnel.ps1 -Hostname wiki.yourdomain.com
#
# Re-running is safe: it reuses an existing tunnel of the same name.

param(
    [Parameter(Mandatory = $true)]
    [string]$Hostname,

    [string]$TunnelName = "copper-vale",
    [int]$Port = 8787
)

$ErrorActionPreference = "Stop"

$cf = "C:\Program Files (x86)\cloudflared\cloudflared.exe"
if (-not (Test-Path $cf)) { $cf = "C:\Program Files\cloudflared\cloudflared.exe" }
if (-not (Test-Path $cf)) {
    $cmd = Get-Command cloudflared -ErrorAction SilentlyContinue
    if ($cmd) { $cf = $cmd.Source } else {
        Write-Host "cloudflared is not installed. Run:" -ForegroundColor Red
        Write-Host "  winget install --id Cloudflare.cloudflared"
        exit 1
    }
}

$cfHome = Join-Path $env:USERPROFILE ".cloudflared"
if (-not (Test-Path (Join-Path $cfHome "cert.pem"))) {
    Write-Host "Not logged in to Cloudflare." -ForegroundColor Red
    Write-Host ""
    Write-Host "Run this first. It opens a browser and asks you to pick the domain"
    Write-Host "you want the tunnel to live under:"
    Write-Host ""
    Write-Host "  & '$cf' tunnel login" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "You need a domain whose DNS is managed by Cloudflare. If you don't"
    Write-Host "have one, a named tunnel isn't possible; see the README for the"
    Write-Host "alternatives."
    exit 1
}

# --- create or reuse the tunnel ------------------------------------------

Write-Host "Looking for an existing '$TunnelName' tunnel..." -ForegroundColor Cyan
$existing = & $cf tunnel list --output json 2>$null | ConvertFrom-Json
$tunnel = $existing | Where-Object { $_.name -eq $TunnelName } | Select-Object -First 1

if ($tunnel) {
    Write-Host "  reusing existing tunnel $($tunnel.id)"
    $tunnelId = $tunnel.id
} else {
    Write-Host "  creating tunnel '$TunnelName'..."
    & $cf tunnel create $TunnelName
    if ($LASTEXITCODE -ne 0) { Write-Host "Failed to create the tunnel." -ForegroundColor Red; exit 1 }
    $tunnel = (& $cf tunnel list --output json | ConvertFrom-Json) |
        Where-Object { $_.name -eq $TunnelName } | Select-Object -First 1
    $tunnelId = $tunnel.id
    Write-Host "  created $tunnelId"
}

$credFile = Join-Path $cfHome "$tunnelId.json"
if (-not (Test-Path $credFile)) {
    Write-Host "Expected credentials at $credFile but it isn't there." -ForegroundColor Red
    exit 1
}

# --- config ---------------------------------------------------------------

$configPath = Join-Path $cfHome "config.yml"
$config = @"
# Generated by dnd-universe/tools/setup_named_tunnel.ps1
tunnel: $tunnelId
credentials-file: $credFile

ingress:
  - hostname: $Hostname
    service: http://127.0.0.1:$Port
  - service: http_status:404
"@
Set-Content -Path $configPath -Value $config -Encoding utf8
Write-Host "Wrote $configPath" -ForegroundColor Green

# --- DNS ------------------------------------------------------------------

Write-Host "Pointing $Hostname at the tunnel..." -ForegroundColor Cyan
& $cf tunnel route dns $TunnelName $Hostname
if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "DNS routing failed. Usually that means the domain isn't in this" -ForegroundColor Yellow
    Write-Host "Cloudflare account, or a record for that hostname already exists."
    Write-Host "An existing record can be replaced from the Cloudflare dashboard."
}

# --- done -----------------------------------------------------------------

Write-Host ""
Write-Host "Setup complete." -ForegroundColor Green
Write-Host ""
Write-Host "Start the tunnel (leave it running):" -ForegroundColor Yellow
Write-Host "  & '$cf' tunnel run $TunnelName"
Write-Host ""
Write-Host "Start the MCP server (separate window, leave it running):" -ForegroundColor Yellow
Write-Host "  cd C:\Claude\dnd-universe"
Write-Host "  `$env:UNIVERSE_MCP_TOKEN = (Get-Content .mcp-token -Raw).Trim()"
Write-Host "  .\.venv\Scripts\python.exe mcp_server.py --http --allowed-host $Hostname"
Write-Host ""
Write-Host "Your players then connect to:" -ForegroundColor Yellow
Write-Host "  https://$Hostname/mcp"
Write-Host "  with header  Authorization: Bearer <the token in .mcp-token>"
Write-Host ""
Write-Host "--allowed-host is required. Without it the transport's DNS rebinding" -ForegroundColor DarkGray
Write-Host "protection returns 421 to every authenticated request." -ForegroundColor DarkGray
